name: React Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_code_with_synk: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run yarn install 
      run: yarn install
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          args: --severity-threshold=high
  build_an_push_docker_image:
    needs: [ test_code_with_synk ]

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag babah11/babahcloud9:react-calculator 
   
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: babah11/babahcloud9:react-calculator

  scan_docker_image_synk:
    needs: [ build_an_push_docker_image ]
    permissions:
     # id-token: read
      contents: read
      packages: read
    runs-on : ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Log in to the Container registry 📦
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Snyk CLI to check for security issues
          # Snyk can be used to break the build when it detects security issues.
          # In this case we want to upload the SAST issues to GitHub Code Scanning
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
    
    - name: Scan Docker image 🐳
      uses: snyk/actions/docker@master
      continue-on-error: false
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
          image: babah11/babahcloud9:react-calculator
          args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif 
      

    - name: Upload Snyk report as sarif 📦
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: snyk.sarif
